# -*- coding: utf-8 -*-
"""BRFSS sandbox.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ccGWr7Ae9U-hP0J0_NDT6-JWUr9z-VK
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
f_name = '/content/drive/MyDrive/Programming for Data Science/Semester Project/Data/LLCP2020XPT/LLCP2020.XPT'
cdc = pd.read_sas(f_name, format = 'xport')

cdc.head(20)
col_names = list(cdc.columns)
col_names

cdc_dict = {col_names[x]:x for x in range(len(col_names))} 
cdc_dict

cdc.loc[cdc['_STATE'] == 51]

cdc.iloc[:, 160:164]

lungCancer = cdc.loc[(cdc['_STATE'].isin([10, 23, 34, 38, 46])) & (cdc['LCSFIRST'].notnull())]
lungCancer.iloc[:, 160:164]

"""Outcome Variable: starts at **CSRVDOC1** ends at **CSRVCTL2** (page 98 to 103 - https://www.cdc.gov/brfss/annual_data/2020/pdf/codebook20_llcp-v2-508.pdf)


"""

# Variables to explore
var_population = ['_SEX,' '_AGEG5YR', '_EDUCAG', 'MARITAL', 'EMPLOY1', '_INCOMG', 'DEAF', 'BLIND', 'DECIDE', 'DIFFWALK', 'DIFFALON', 'RACEPRV', 'BMI5CAT']
var_cancer_related = ['CSRVTRT3', 'CSRVSUM', 'CSRVRTRN', 'CSRVINST', 'CSRVINSR', 'CSRVDEIN', 'CSRVPAIN', 'CSRVCTL2']

# Subsetting cancer types
cancerType = cdc.loc[cdc.CNCRTYP1.notnull()]

# Proportion of people who have cancer
(len(cancerType)/len(cdc))*100

# Porportion of people have lung cancer
(len(lungCancer)/len(cdc))*100

# Subetting for lung cancer
lungCancer = cancerType[cancerType.CNCRTYP1 == 24]

# Matches no. in codebook
lungCancer

lungCancer = lungCancer[['_SEX', '_AGEG5YR', '_EDUCAG', 'MARITAL', 'EMPLOY1', '_INCOMG', 'DECIDE', 'DIFFWALK', 'DIFFALON', '_RACEPRV', 'MENTHLTH', 'PHYSHLTH', 'POORHLTH', 'CSRVSUM', 'CSRVRTRN', 'CSRVINSR', 'CSRVPAIN']]

lungCancer.to_csv('/content/drive/MyDrive/Programming for Data Science/Semester Project/Data/lung_cancer.csv', index=False)